
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/explorer-api

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-]
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit Tests
          command: npm run test
      - persist_to_workspace:
          root: ~/
          paths:
            - explorer-api

  deploy:
      docker:
        - image: circleci/node:8
      working_directory: ~/explorer-api

      steps:
        - setup_remote_docker
        - attach_workspace:
            at: ~/
        - run:
            name: Install AWS CLI
            command: sudo apt-get install python-dev build-essential python-pip && sudo pip install awscli
        - run: cd ~/explorer-api
        - run:
            name: Prune dependencies
            command: npm prune --production
        - run:
            name: Copy Environment Variables
            command: |
                ENV_FILE=.env
                echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $ENV_FILE
                echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $ENV_FILE
        - run:
            name: Build Docker Container
            command: docker build -t explorer-api .
        - run:
            name: Push Docker Image to ECR
            command: |
                DOCKER_IMAGE=explorer-api
                AWS_REGION=us-east-1
                AWS_ACCOUNT_ID=751958071466
                DOCKER_TAG=latest
                # Login to AWS
                aws configure set region $AWS_REGION
                $(aws ecr get-login --no-include-email)
                # Tag and push docker image
                docker tag $DOCKER_IMAGE:$DOCKER_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$DOCKER_TAG
                docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$DOCKER_TAG

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master